### ISSUE TITLE
Edit functionality broken

### ISSUE THREAD

**Issue by mohnen** [coatue/SlickGrid#53]
I switched from [6pac SlickGrid](https://www.npmjs.com/package/slickgrid)  to your repository to use the fixedColumn functionality. A custom editor which worked with the 6pac SlickGrid broke during this switch.
I was getting an `Uncaught TypeError: this.updateRow is not a function` at `slickgrid2\dist\grid.js:3385 `.

I have traced down the error to the method `SlickGrid.commitCurrentEdit (slickgrid2\dist\grid.js:3407)`. The problems are the `execute` and `undo` functions inside the `editCommand` object. When these functions are executed, `this` refers to the `editCommand` object but in the call `this.updateRow(this.row)`  the first `this` must be the SlickGrid object.

I have attached a fixed version which I include in addition to your code.
`const SlickGrid = require('slickgrid2').SlickGrid;`
`require('./slickgrid.editor.fix.js')(SlickGrid);`

[slickgrid.editor.fix.js.txt](https://github.com/coatue-oss/SlickGrid/files/1003463/slickgrid.editor.fix.js.txt)

**Comment by ghost** [comment]
hi @mohnen thanks for your contribution, I'll get to this at some point!

**Comment by ghost** [comment]
ok got to it, the changes are addressed in https://github.com/coatue-oss/slickgrid2/commit/5db83db5a63f191eff79e81d55c516820e97bfc9

would appreciate a PR in future even if it's to the JS code - i can translate to TS code.

**Comment by mohnen** [comment]
@khoomeister: Works fine for me, thanks for the fix!
